### ISSUE TITLE
add userstamps to timestamps()

### ISSUE THREAD

**Issue by arnoldjp57** [WildSideUK/Laravel-Userstamps#4]
Can you add the created_by and updated_by fields to timestamps() so that all new tables created will include the userstamps fields

**Comment by mattmcdonald-uk** [comment]
I've considered adding something along those lines - will try to take a look at it some point - happy to accept a PR though!

**Comment by arnoldjp57** [comment]
:-)    What is a PR?

**Comment by mattmcdonald-uk** [comment]
Handy section on Pull Requests (PRs) here https://guides.github.com/activities/contributing-to-open-source

**Comment by harry-synergi** [comment]
I'm aware the issue is old & closed but I've documented the way to combine timestamps() & userstamps() below. This is tested on 5.7 but any version of Laravel that has Blueprint able to use Macro should be ok.

### AppServiceProvider:
```php
Blueprint::macro('userTimeStamps', function() {
            $this->timestamps();
            $this->unsignedBigInteger('created_by')->nullable();
            $this->unsignedBigInteger('updated_by')->nullable();
            $this->unsignedBigInteger('deleted_by')->nullable();
        });
```

The created_by, updated_by & deleted_by also use unsignedBigInteger as this is consistent with the id columns. You could also change them to foreign keys if you wished.

You then simply need to do

```php
$table->userTimeStamps();
```

inside your migrations.

**Comment by mattmcdonald-uk** [comment]
Good spot on the `unsignedBigInteger` @harry-synergi - have updated the readme.

**Comment by harry-synergi** [comment]
> Good spot on the `unsignedBigInteger` @harry-synergi - have updated the readme.

No problem. I'm also confused why you're doing `default(null)` when `nullable()` should take care of that? Is this due to the strict DB mode in laravel 5.3?

**Comment by mattmcdonald-uk** [comment]
> > Good spot on the `unsignedBigInteger` @harry-synergi - have updated the readme.
> 
> No problem. I'm also confused why you're doing `default(null)` when `nullable()` should take care of that? Is this due to the strict DB mode in laravel 5.3?

Nope - just a mistake! ☺️
